#define MEME_DIR "/home/thinnerichs/meme"
#define DATA_DIR "/home/thinnerichs/meme/share/meme-5.1.0" 
#define BIN_DIR "/home/thinnerichs/meme/bin" 
#define LIBEXEC_DIR "/home/thinnerichs/meme/libexec/meme-5.1.0" 
#define TEMP_DIR "" 
